"""newMigration

Revision ID: 234eacd1e08e
Revises: d6f8a36dcba3
Create Date: 2022-06-15 18:46:01.846367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234eacd1e08e'
down_revision = 'd6f8a36dcba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
